name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-clang:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 3.1
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.1.x
    - name: Setup
      run: |
        sudo apt-get install -y make clang
        gem install rice
    - name: Build with clang
      run: |
        ruby extconf.rb
        make
    - name: Build gem
      run: |
        gem build huffman_tw.gemspec
    - name: Install and run gem
      run: |
        gem install ./huffman_tw-*.gem
        ruby -e 'require "huffman_tw";exit(1) unless Huffman.new.compress("hello") == [174, 149, 19, 92, 9, 87, 194, 22, 41, 110, 0]'
